- name: install nginx
  apt:
    name: nginx
    state: present
  become: true
   
- name: deploy nginx default config file
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/sites-enabled/wordpress
  notify:
    - 'restart nginx'
  become: true

           
